# Generated by Django 4.2.2 on 2023-08-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_name',
        ),
        migrations.AddField(
            model_name='post',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
